package heron.Boults;

import backtype.storm.tuple.Tuple;
import heron.Tools.Rankings;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * This bolt merges incoming {@link Rankings}.
 * <p/>
 * It can be used to merge intermediate rankings generated by {@link IntermediateRankings} into a final,
 * consolidated ranking. To do so, configure this bolt with a globalGrouping on {@link IntermediateRankings}.
 */
public final class TotalRankings extends AbstractRanker {
  //String hashtag[]=new String[10];
  //int Count[]={0,0,0,0,0,0,0,0,0,0};
  private static final long serialVersionUID = -8447525895532302198L;
  private static final Logger LOG = LogManager.getLogger(TotalRankings.class);

  public TotalRankings() {
    super();
  }

  public TotalRankings(int topN) {
    super(topN);
  }

  public TotalRankings(int topN, int emitFrequencyInSeconds) {
    super(topN, emitFrequencyInSeconds);
  }

  @Override
  void updateRankingsWithTuple(Tuple tuple) {
    Rankings rankingsToBeMerged = (Rankings) tuple.getValue(0);
    super.getRankings().updateWith(rankingsToBeMerged);
    super.getRankings().pruneZeroCounts();


  }

  @Override
  Logger getLogger() {
    return LOG;
  }

}
